[package]
name = "validate-cert"
version = "0.1.0"
edition = "2021"

[dependencies]
x509-parser = { version = "0.17", features = ["validate", "verify"] }
clap = "4.5"
anyhow = "1.0"
hex = "0.4"
colored = "3.0"
reqwest = { version = "0.12", features = ["blocking"] }
ocsp = "0.4"